server:
  port: 8081
spring:
  main:
    banner-mode: off
  profiles:
    active:
    - dev
  thymeleaf:
    encoding: UTF-8
    mode: HTML
---
spring:
  config:
    activate:
      on-profile:
      - testU
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: never   
      encoding: UTF-8
---
spring:
  jpa:
    properties:
      '[javax.persistence.validation.mode]': AUTO
---
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: 'jdbc:h2:~/PID_DB/pidDB_2223'
    username: sa
    password: 

  sql:
    init:
      mode: always
      platform: h2
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
      
    database-platform: 'org.hibernate.dialect.H2Dialect'
    
    defer-datasource-initialization: true
  h2:
    
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
logging:
  level:
    '[org.isfce.pid.controller]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"


